import 'dart:ui';

import 'package:flutter/foundation.dart';

import '../geometry/geometry.dart';
import '../tools/selection_tool.dart';
import '../tools/tool.dart';
import 'layer.dart';
import 'metric_unit.dart';

const _unsetLabel = Object();
const _defaultLayer = Layer(id: '0', name: 'Layer 0');

/// The state of the viewport.
///
/// It contains all the [layers] being displayed,
/// the current [zoom] and the [panOffset].
@immutable
class ViewportState {
  /// The default [ViewportState] constructor
  const ViewportState({
    this.layers = const [_defaultLayer],
    this.activeLayerId = '0',
    this.toolGeometries = const [],
    this.snappingGeometries = const [],
    this.zoom = 1.0,
    this.panOffset = .zero,
    this.cursorPosition = .zero,
    this.selectedTool = const SelectionTool(),
    this.selectedUnit = MetricUnit.mm,
    this.overlayLabel,
    this.userInput = '',
  });

  /// The drawing layers.
  ///
  /// Each layer owns its own list of geometries.
  /// Layers are rendered in list order (index 0 = bottom).
  final List<Layer> layers;

  /// The ID of the layer that receives new geometry.
  final String activeLayerId;

  /// The tool [Geometry] list.
  ///
  /// These geometries are generated by the active tool and are removed
  /// once the tool finishes its action.
  final List<Geometry> toolGeometries;

  /// The snapping [Geometry] list.
  ///
  /// These geometries are used to represent snapping areas.
  final List<Geometry> snappingGeometries;

  /// The current zoom.
  final double zoom;

  /// The current pan (movement) offset.
  final Offset panOffset;

  /// The position of the cursor.
  final Offset cursorPosition;

  /// The selected tool.
  final Tool selectedTool;

  /// The selected project unit used for value input interpretation.
  final MetricUnit selectedUnit;

  /// Overlay text for tool output (measurement results, selection properties).
  final String? overlayLabel;

  /// Whether or not show value picker;
  final String userInput;

  /// Creates a copy of [ViewportState] with replaced values.
  ///
  /// For [selectedTool], passing `null` explicitly clears the selected tool.
  /// Omitting [selectedTool] preserves the previous value.
  ViewportState copyWith({
    List<Layer>? layers,
    String? activeLayerId,
    List<Geometry>? toolGeometries,
    List<Geometry>? snappingGeometries,
    double? zoom,
    Offset? panOffset,
    Offset? cursorPosition,
    Tool? selectedTool,
    MetricUnit? selectedUnit,
    Object? overlayLabel = _unsetLabel,
    String? userInput,
  }) {
    return ViewportState(
      layers: layers ?? this.layers,
      activeLayerId: activeLayerId ?? this.activeLayerId,
      toolGeometries: toolGeometries ?? this.toolGeometries,
      snappingGeometries: snappingGeometries ?? this.snappingGeometries,
      zoom: zoom ?? this.zoom,
      panOffset: panOffset ?? this.panOffset,
      cursorPosition: cursorPosition ?? this.cursorPosition,
      selectedTool: selectedTool ?? this.selectedTool,
      selectedUnit: selectedUnit ?? this.selectedUnit,
      overlayLabel: overlayLabel == _unsetLabel
          ? this.overlayLabel
          : overlayLabel as String?,
      userInput: userInput ?? this.userInput,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is ViewportState &&
            listEquals(layers, other.layers) &&
            activeLayerId == other.activeLayerId &&
            listEquals(toolGeometries, other.toolGeometries) &&
            listEquals(snappingGeometries, other.snappingGeometries) &&
            zoom == other.zoom &&
            panOffset == other.panOffset &&
            cursorPosition == other.cursorPosition &&
            selectedTool == other.selectedTool &&
            selectedUnit == other.selectedUnit &&
            overlayLabel == other.overlayLabel &&
            userInput == other.userInput;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      Object.hashAll(layers),
      activeLayerId,
      Object.hashAll(toolGeometries),
      Object.hashAll(snappingGeometries),
      zoom,
      panOffset,
      cursorPosition,
      selectedTool,
      selectedUnit,
      overlayLabel,
      userInput,
    ]);
  }
}
