import 'dart:ui';

import 'package:flutter/foundation.dart';

import '../geometry/geometry.dart';
import '../tools/selection_tool.dart';
import '../tools/tool.dart';
import 'metric_unit.dart';

/// The state of the viewport.
///
/// It contains all the [geometries] being displayed,
/// the current [zoom] and the [panOffset].
@immutable
class ViewportState {
  /// The default [ViewportState] constructor
  const ViewportState({
    this.geometries = const [],
    this.toolGeometries = const [],
    this.snappingGeometries = const [],
    this.zoom = 1.0,
    this.panOffset = .zero,
    this.cursorPosition = .zero,
    this.selectedTool = const SelectionTool(),
    this.selectedUnit = MetricUnit.mm,
    this.userInput = '',
  });

  /// The [Geometry] list of the viewport.
  ///
  /// All the given geometries will be rendered in the viewport,
  /// given that they intersect the viewport rect.
  final List<Geometry> geometries;

  /// The tool [Geometry] list.
  ///
  /// These geometries are generated by the active tool and are removed
  /// once the tool finishes its action.
  final List<Geometry> toolGeometries;

  /// The snapping [Geometry] list.
  ///
  /// These geometries are used to represent snapping areas.
  final List<Geometry> snappingGeometries;

  /// The current zoom.
  final double zoom;

  /// The current pan (movement) offset.
  final Offset panOffset;

  /// The position of the cursor.
  final Offset cursorPosition;

  /// The selected tool.
  final Tool selectedTool;

  /// The selected project unit used for value input interpretation.
  final MetricUnit selectedUnit;

  /// Whether or not show value picker;
  final String userInput;

  /// Creates a copy of [ViewportState] with replaced values.
  ///
  /// For [selectedTool], passing `null` explicitly clears the selected tool.
  /// Omitting [selectedTool] preserves the previous value.
  ViewportState copyWith({
    List<Geometry>? geometries,
    List<Geometry>? toolGeometries,
    List<Geometry>? snappingGeometries,
    double? zoom,
    Offset? panOffset,
    Offset? cursorPosition,
    Tool? selectedTool,
    MetricUnit? selectedUnit,
    String? userInput,
  }) {
    return ViewportState(
      geometries: geometries ?? this.geometries,
      toolGeometries: toolGeometries ?? this.toolGeometries,
      snappingGeometries: snappingGeometries ?? this.snappingGeometries,
      zoom: zoom ?? this.zoom,
      panOffset: panOffset ?? this.panOffset,
      cursorPosition: cursorPosition ?? this.cursorPosition,
      selectedTool: selectedTool ?? this.selectedTool,
      selectedUnit: selectedUnit ?? this.selectedUnit,
      userInput: userInput ?? this.userInput,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is ViewportState &&
            listEquals(geometries, other.geometries) &&
            listEquals(toolGeometries, other.toolGeometries) &&
            listEquals(snappingGeometries, other.snappingGeometries) &&
            zoom == other.zoom &&
            panOffset == other.panOffset &&
            cursorPosition == other.cursorPosition &&
            selectedTool == other.selectedTool &&
            selectedUnit == other.selectedUnit &&
            userInput == other.userInput;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      Object.hashAll(geometries),
      Object.hashAll(toolGeometries),
      Object.hashAll(snappingGeometries),
      zoom,
      panOffset,
      cursorPosition,
      selectedTool,
      selectedUnit,
      userInput,
    ]);
  }
}
